name: Build and push image

on:
  push:
    branches:
      - testnet
      - develop
      - staging
      - main

jobs:
  checkout-actions:
    permissions:
      id-token: write
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github actions
        uses: actions/checkout@v3
        with:
          repository: lifinance/github-actions
          ssh-key: ${{ secrets.DEPLOY_SSH }}
          ref: 'main'
          path: github-actions
      - name: Trigger reusable workflow
        uses: ./github-actions/.github/workflows/build-and-push-docker-with-args.yaml
        with:
          registry: 403372804574.dkr.ecr.us-east-2.amazonaws.com/lifi-docker-repo
          image-name: 'lifinance/jumper-exchange'
        secrets:
          deploy_key: ${{ secrets.DEPLOY_SSH }}